name: auth_with_bloc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Text
  google_fonts: ^4.0.4

  #Local Storage
  flutter_secure_storage: ^8.0.0
  
  #Network
  dio: ^5.1.1

  #State Management
  flutter_bloc: ^8.1.2

  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
